apiVersion: apps/v1
data:
  spec:
    template:
      $patch: replace
      metadata:
        creationTimestamp: null
        labels:
          component: azure-cni-networkmonitor
          tier: node
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.azure.com/cluster
                  operator: Exists
        containers:
        - env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          image: mcr.microsoft.com/containernetworking/networkmonitor:v1.1.8
          imagePullPolicy: IfNotPresent
          name: azure-cni-networkmonitor
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/run
            name: ebtables-rule-repo
          - mountPath: /var/log
            name: log
        dnsPolicy: ClusterFirst
        hostNetwork: true
        nodeSelector:
          beta.kubernetes.io/os: linux
        priorityClassName: system-node-critical
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        volumes:
        - hostPath:
            path: /var/log
            type: ""
          name: log
        - hostPath:
            path: /var/run/
            type: ""
          name: ebtables-rule-repo
kind: ControllerRevision
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","component":"azure-cni-networkmonitor","kubernetes.io/cluster-service":"true","tier":"node"},"name":"azure-cni-networkmonitor","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"component":"azure-cni-networkmonitor","tier":"node"}},"template":{"metadata":{"labels":{"component":"azure-cni-networkmonitor","tier":"node"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"labelSelector":null,"matchExpressions":[{"key":"kubernetes.azure.com/cluster","operator":"Exists"}]}]}}},"containers":[{"env":[{"name":"HOSTNAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"spec.nodeName"}}}],"image":"mcr.microsoft.com/containernetworking/networkmonitor:v1.1.8","name":"azure-cni-networkmonitor","securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/run","name":"ebtables-rule-repo"},{"mountPath":"/var/log","name":"log"}]}],"hostNetwork":true,"nodeSelector":{"beta.kubernetes.io/os":"linux"},"priorityClassName":"system-node-critical","tolerations":[{"key":"CriticalAddonsOnly","operator":"Exists"},{"effect":"NoExecute","operator":"Exists"},{"effect":"NoSchedule","operator":"Exists"}],"volumes":[{"hostPath":{"path":"/var/log"},"name":"log"},{"hostPath":{"path":"/var/run/"},"name":"ebtables-rule-repo"}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":1},"type":"RollingUpdate"}}}
  creationTimestamp: "2021-03-10T06:00:46Z"
  labels:
    component: azure-cni-networkmonitor
    controller-revision-hash: 64fbfdb6b4
    tier: node
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
      f:metadata:
        f:annotations:
          .: {}
          f:deprecated.daemonset.template.generation: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:component: {}
          f:controller-revision-hash: {}
          f:tier: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"fe62610b-5db1-4709-a264-0ffa5bb66d40"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:revision: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-10T06:00:46Z"
  name: azure-cni-networkmonitor-64fbfdb6b4
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: azure-cni-networkmonitor
    uid: fe62610b-5db1-4709-a264-0ffa5bb66d40
revision: 1
