apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2021-03-10T06:01:56Z"
  creationTimestamp: "2021-03-10T06:00:46Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:labels:
          .: {}
          f:addonmanager.kubernetes.io/mode: {}
          f:kubernetes.io/cluster-service: {}
      f:subsets: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-10T06:01:56Z"
  name: healthmodel-replicaset-service
  namespace: kube-system
subsets:
- addresses:
  - ip: 10.2.1.111
    nodeName: aks-agentpool-38943226-vmss000000
    targetRef:
      kind: Pod
      name: omsagent-rs-7bbd897856-p6z94
      namespace: kube-system
      resourceVersion: "539"
      uid: 861b43a8-0f37-4d01-8bc3-f4b9b935297f
  ports:
  - port: 25227
    protocol: TCP
