apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"kube-controller-manager-7c5cdb7645-xwp8b_63b6d2ed-b307-4deb-9ff4-ac7422a25277","leaseDurationSeconds":15,"acquireTime":"2021-03-10T06:00:24Z","renewTime":"2021-03-11T08:40:27Z","leaderTransitions":0}'
  creationTimestamp: "2021-03-10T06:00:24Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:control-plane.alpha.kubernetes.io/leader: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-10T06:00:24Z"
  name: kube-controller-manager
  namespace: kube-system
