addressType: IPv4
apiVersion: discovery.k8s.io/v1beta1
endpoints:
- addresses:
  - 10.2.1.157
  conditions:
    ready: true
  targetRef:
    kind: Pod
    name: azure-policy-webhook-578df58bcd-qc4gs
    namespace: kube-system
    resourceVersion: "203416"
    uid: 45019d8d-e5a2-432f-affd-c0e17b13bf5d
  topology:
    kubernetes.io/hostname: aks-openhacknp-38943226-vmss000000
    topology.kubernetes.io/region: eastasia
    topology.kubernetes.io/zone: "0"
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2021-03-11T05:15:04Z"
  creationTimestamp: "2021-03-11T05:15:02Z"
  generateName: azure-policy-webhook-service-
  labels:
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: azure-policy-webhook-service
  managedFields:
  - apiVersion: discovery.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:addressType: {}
      f:endpoints: {}
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:endpointslice.kubernetes.io/managed-by: {}
          f:kubernetes.io/service-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"b6954f91-359c-46d7-bc92-477eb14c7708"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:ports: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-11T05:15:04Z"
  name: azure-policy-webhook-service-tzh4g
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: azure-policy-webhook-service
    uid: b6954f91-359c-46d7-bc92-477eb14c7708
ports:
- name: webhook
  port: 9449
  protocol: TCP
