apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2021-03-10T06:02:02Z"
  creationTimestamp: "2021-03-10T06:00:46Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Metrics-server
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:labels:
          .: {}
          f:addonmanager.kubernetes.io/mode: {}
          f:kubernetes.io/cluster-service: {}
          f:kubernetes.io/name: {}
      f:subsets: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-10T06:01:43Z"
  name: metrics-server
  namespace: kube-system
subsets:
- addresses:
  - ip: 10.2.1.100
    nodeName: aks-agentpool-38943226-vmss000000
    targetRef:
      kind: Pod
      name: metrics-server-58fdc875d5-zxq8m
      namespace: kube-system
      resourceVersion: "567"
      uid: 16ab2fec-e845-483c-863e-6e759aab1e96
  ports:
  - port: 443
    protocol: TCP
