apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"azure-policy-webhook-service","namespace":"kube-system"},"spec":{"ports":[{"name":"webhook","port":443,"targetPort":9449}],"selector":{"app":"azure-policy-webhook"}}}
  creationTimestamp: "2021-03-11T05:15:02Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:addonmanager.kubernetes.io/mode: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":443,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2021-03-11T05:15:02Z"
  name: azure-policy-webhook-service
  namespace: kube-system
spec:
  clusterIP: 10.0.29.103
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: 9449
  selector:
    app: azure-policy-webhook
  sessionAffinity: None
  type: ClusterIP
