apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"healthmodel-replicaset-service","namespace":"kube-system"},"spec":{"ports":[{"port":25227,"protocol":"TCP","targetPort":"in-rs-tcp"}],"selector":{"rsName":"omsagent-rs"}}}
  creationTimestamp: "2021-03-10T06:00:46Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:addonmanager.kubernetes.io/mode: {}
          f:kubernetes.io/cluster-service: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":25227,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:rsName: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2021-03-10T06:00:46Z"
  name: healthmodel-replicaset-service
  namespace: kube-system
spec:
  clusterIP: 10.0.131.245
  ports:
  - port: 25227
    protocol: TCP
    targetPort: in-rs-tcp
  selector:
    rsName: omsagent-rs
  sessionAffinity: None
  type: ClusterIP
