apiVersion: apps/v1
data:
  spec:
    template:
      $patch: replace
      metadata:
        creationTimestamp: null
        labels:
          app: csi-secrets-store-provider-azure
          app.kubernetes.io/instance: csi
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: csi-secrets-store-provider-azure
          app.kubernetes.io/version: 0.0.13
          helm.sh/chart: csi-secrets-store-provider-azure-0.0.17
      spec:
        containers:
        - args:
          - --endpoint=unix:///provider/azure.sock
          image: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.13
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                - rm /provider/azure.sock
          livenessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=unix:///provider/azure.sock
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: provider-azure-installer
          readinessProbe:
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=unix:///provider/azure.sock
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /provider
            name: provider-vol
          - mountPath: /var/lib/kubelet/pods
            mountPropagation: HostToContainer
            name: mountpoint-dir
        dnsPolicy: ClusterFirst
        hostNetwork: true
        nodeSelector:
          kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: csi-secrets-store-provider-azure
        serviceAccountName: csi-secrets-store-provider-azure
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /etc/kubernetes/secrets-store-csi-providers
            type: ""
          name: provider-vol
        - hostPath:
            path: /var/lib/kubelet/pods
            type: ""
          name: mountpoint-dir
kind: ControllerRevision
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    meta.helm.sh/release-name: csi
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-03-10T06:30:39Z"
  labels:
    app: csi-secrets-store-provider-azure
    app.kubernetes.io/instance: csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-secrets-store-provider-azure
    app.kubernetes.io/version: 0.0.13
    controller-revision-hash: 5cbff7b9
    helm.sh/chart: csi-secrets-store-provider-azure-0.0.17
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
      f:metadata:
        f:annotations:
          .: {}
          f:deprecated.daemonset.template.generation: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:controller-revision-hash: {}
          f:helm.sh/chart: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"a4141eac-50ba-4b31-9e5e-ec551f511143"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:revision: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-10T06:30:39Z"
  name: csi-csi-secrets-store-provider-azure-5cbff7b9
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: csi-csi-secrets-store-provider-azure
    uid: a4141eac-50ba-4b31-9e5e-ec551f511143
revision: 1
