addressType: IPv4
apiVersion: discovery.k8s.io/v1beta1
endpoints: null
kind: EndpointSlice
metadata:
  creationTimestamp: "2021-03-11T02:49:59Z"
  generateName: insurance-
  labels:
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: insurance
  managedFields:
  - apiVersion: discovery.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:addressType: {}
      f:endpoints: {}
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:endpointslice.kubernetes.io/managed-by: {}
          f:kubernetes.io/service-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"dfdbf9bf-9c0e-48d3-93a3-b8b40f529e73"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:ports: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-11T03:19:41Z"
  name: insurance-qwbl7
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: insurance
    uid: dfdbf9bf-9c0e-48d3-93a3-b8b40f529e73
ports: null
