addressType: IPv4
apiVersion: discovery.k8s.io/v1beta1
endpoints: null
kind: EndpointSlice
metadata:
  creationTimestamp: "2021-03-11T03:19:46Z"
  generateName: insurance2-
  labels:
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: insurance2
  managedFields:
  - apiVersion: discovery.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:addressType: {}
      f:endpoints: {}
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:endpointslice.kubernetes.io/managed-by: {}
          f:kubernetes.io/service-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"a8462423-389f-4376-83cd-ea314906c654"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:ports: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-11T03:33:47Z"
  name: insurance2-smv79
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: insurance2
    uid: a8462423-389f-4376-83cd-ea314906c654
ports: null
