apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2021-03-10T07:26:40Z"
  creationTimestamp: "2021-03-10T07:26:40Z"
  labels:
    app: user-java
    env: OpenHack
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:labels:
          .: {}
          f:app: {}
          f:env: {}
      f:subsets: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-10T07:26:40Z"
  name: user-java
  namespace: default
subsets:
- addresses:
  - ip: 10.2.1.109
    nodeName: aks-agentpool-38943226-vmss000000
    targetRef:
      kind: Pod
      name: user-java-c498df978-46wlz
      namespace: default
      resourceVersion: "12607"
      uid: 35550997-b162-4d0b-8fc8-5430e8dbbbf1
  - ip: 10.2.1.112
    nodeName: aks-agentpool-38943226-vmss000000
    targetRef:
      kind: Pod
      name: user-java-c498df978-kdsqv
      namespace: default
      resourceVersion: "12600"
      uid: 1bd94b3c-c8de-4973-b753-1ec041d375b7
  - ip: 10.2.1.119
    nodeName: aks-agentpool-38943226-vmss000000
    targetRef:
      kind: Pod
      name: user-java-c498df978-gvdhl
      namespace: default
      resourceVersion: "12604"
      uid: 3800f3f2-ca18-43d7-91c9-8acf676f9cf2
  ports:
  - name: http
    port: 80
    protocol: TCP
