apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"secrets-store.csi.x-k8s.io/v1alpha1","kind":"SecretProviderClass","metadata":{"annotations":{},"name":"aks-keyvault-openhack","namespace":"default"},"spec":{"parameters":{"cloudName":"","keyvaultName":"AKS-KeyVault-openhack","objects":"array:\n  - |\n    objectName: sqlfqdn                                        \n    objectType: secret                                                \n    objectVersion: \"\"\n    objectAlias: \"SQL_SERVER\"                                                \n  - |\n    objectName: sqluser\n    objectType: secret\n    objectVersion: \"\"\n    objectAlias: \"SQL_USER\"\n  - |\n    objectName: sqlpass\n    objectType: secret\n    objectVersion: \"\"\n    objectAlias: \"SQL_PASSWORD\"\n  - |\n    objectName: sqldbname\n    objectType: secret\n    objectVersion: \"\"\n    objectAlias: \"SQL_DBNAME\"\n","tenantId":"0514a5b3-9d6b-4654-b620-dcfcc7491bee","usePodIdentity":"false","useVMManagedIdentity":"false","userAssignedIdentityID":""},"provider":"azure"}}
  creationTimestamp: "2021-03-10T06:31:25Z"
  managedFields:
  - apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:parameters:
          .: {}
          f:cloudName: {}
          f:keyvaultName: {}
          f:objects: {}
          f:tenantId: {}
          f:usePodIdentity: {}
          f:useVMManagedIdentity: {}
          f:userAssignedIdentityID: {}
        f:provider: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-10T06:31:25Z"
  name: aks-keyvault-openhack
  namespace: default
spec:
  parameters:
    cloudName: ""
    keyvaultName: AKS-KeyVault-openhack
    objects: "array:\n  - |\n    objectName: sqlfqdn                                        \n
      \   objectType: secret                                                \n    objectVersion:
      \"\"\n    objectAlias: \"SQL_SERVER\"                                                \n
      \ - |\n    objectName: sqluser\n    objectType: secret\n    objectVersion: \"\"\n
      \   objectAlias: \"SQL_USER\"\n  - |\n    objectName: sqlpass\n    objectType:
      secret\n    objectVersion: \"\"\n    objectAlias: \"SQL_PASSWORD\"\n  - |\n
      \   objectName: sqldbname\n    objectType: secret\n    objectVersion: \"\"\n
      \   objectAlias: \"SQL_DBNAME\"\n"
    tenantId: 0514a5b3-9d6b-4654-b620-dcfcc7491bee
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
  provider: azure
