apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-03-11T03:19:46Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-11T03:19:46Z"
  name: insurance2
  namespace: default
spec:
  clusterIP: 10.0.61.36
  ports:
  - name: insurance-http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: insurance2
  sessionAffinity: None
  type: ClusterIP
