apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  creationTimestamp: "2021-03-10T06:00:16Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.coordination.k8s.io
spec:
  group: coordination.k8s.io
  groupPriorityMinimum: 16500
  version: v1
  versionPriority: 15
