apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: kube-backups
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-03-11T07:18:07Z"
  labels:
    app: katafygio
    app.kubernetes.io/managed-by: Helm
    chart: katafygio-0.5.1
    heritage: Helm
    release: kube-backups
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:roleRef:
        f:apiGroup: {}
        f:kind: {}
        f:name: {}
      f:subjects: {}
    manager: Go-http-client
    operation: Update
    time: "2021-03-11T07:18:07Z"
  name: kube-backups-katafygio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-backups-katafygio
subjects:
- kind: ServiceAccount
  name: kube-backups-katafygio
  namespace: default
