apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"app":"prometheus"},"name":"system:prometheus"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"system:prometheus"},"subjects":[{"apiGroup":"rbac.authorization.k8s.io","kind":"User","name":"hcpService"}]}
  creationTimestamp: "2021-03-10T06:00:39Z"
  labels:
    app: prometheus
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:roleRef:
        f:apiGroup: {}
        f:kind: {}
        f:name: {}
      f:subjects: {}
    manager: manager
    operation: Update
    time: "2021-03-10T06:00:39Z"
  name: system:prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:prometheus
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: hcpService
