apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  annotations:
    meta.helm.sh/release-name: csi
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-03-10T06:30:39Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: storage.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
      f:spec:
        f:attachRequired: {}
        f:podInfoOnMount: {}
        f:volumeLifecycleModes:
          .: {}
          v:"Ephemeral": {}
    manager: Go-http-client
    operation: Update
    time: "2021-03-10T06:30:39Z"
  name: secrets-store.csi.k8s.io
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
  - Ephemeral
