apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1beta1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{},"labels":{"admissions.enforcer/disabled":"true"},"name":"aks-webhook-admission-controller"},"webhooks":[{"clientConfig":{"caBundle":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2VENDQXRHZ0F3SUJBZ0lSQUxRNGdtZEIxMFZXTXdaZVIxU3c5UW93RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdJQmNOTWpFd016RXdNRFUwTlRReldoZ1BNakExTVRBek1UQXdOVFUxTkROYQpNQTB4Q3pBSkJnTlZCQU1UQW1OaE1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBCjBvVWthNnV3cGFERHBNMXIwcitKaEFWcG1JUzFpb3RlZHlMbGlsdDBJOVZBUGtCWFA3TVZUR0tkby8xdzdtS3kKdm9kU0JZNHRidzZ6SVhqd3N5TzhSZzYrYjFkTTVBL2kxbDVmbzRmbmtuOURFM0toSzRZTnAzZlhRVVMvbzJFSAozNFFHMyt5dmtwWThkVFhvRTdkM05EM3N3RTVYRHJqVlpyVmx2YXgwUzlxd1dqM2owQXRYV3FlQ0QxYWEyQndYCmMvcjNuVis4OFNlaTFjcDVTR1ljWEROYlRTQU1HQm9SdVM4a0dRYi9za3N0ZkxsSHlzVVM3ZmJaL2pKMEJlUDIKcWErd2l3OWpPOG9RMWVmLzRoTjJLeVduclNjY2hCeHdMNzdDMGlsUTlzWEozUW9PNFhRa0MwUGpNMnlkN2NFWApHZXhHV0NLMzAvay8rVWVwSU11N25BSExwVHlBUGd0dDdOVW1wN045bStsSWNyV0s3Q0MwREhmWlEycHhuV1FtCnhsaDVheVd4b3pSa2o2RC9wTHRIWDRqZDNrbmkxckJnSEZabzRFdHZ1MmNPU2YrT0txSGZ6dXBXbXZuM21FL0kKcU14d0tDaGhYZFV1WlBuRXhTNGpYWk1kZHdXTlZhNVRKdSthbkxwMVcrOForbGwwRHVneUhiSVRweDFCeXdoRwp5SkwwSEJPYWpuQTQ4ekFLSE52RDBVMUo4YTR1M09xa1BIRnhxR1QxY3c4dXVKWVZET1BFNWE4ZEpGcncwV0FSCmNoQjV1QlArb0N1UEI4M3JITCtrb1FKRlBnc3JwRlhBN3NEZUhid0Vrb2FZOC9pcW5BVkVyOGxnbllKVDJNTjMKd0VsUjVLNkl3a0VCM29hOGUyL2tnQUpDOU5yUUNCQU45SkY5bEMrZ2FIc0NBd0VBQWFOQ01FQXdEZ1lEVlIwUApBUUgvQkFRREFnS2tNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGQXFKNjloV2I5TG9sbUhFCjFndHczMjRpd3l5Zk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQVVIeGFQenlQYk5PSkRxZTdJM2xhUmtGcGUKcW9hYjFnK2FiVW1Ua0JiOW0rQmxlT1hNNUczd1haZXhicFlDaEozM1NKdWVPRTU4NFIxa1lncjQzVEVLTGttQgo1VHJRYklGcS9TT1Rha0RLbmhmRXFCRHBYZTQxeE5MTzM3S1Jnd2ZDZ0VBUU9Zbm85Szh5REdsMk9yY092SkViClFmakNsR2phMGt0NnBFanYzdmlKSnR2S05LL0VESFhOYXRsZ2k5U2daUnM4NkkxOW1mcmI0ZVBpWldKU3ZyVGcKdFk5eFdJNTNhYmxEUXczRndvNmZPdjBvWDN3UHhZdkp3OGFjSEM0WW1vWXcvQWtpUUxRV0NUV1ZQRG1OZGVrbwo2WlVjK2RVeG9oNmhOZVg3V1creXNxc1cwK1gwMjBiemVIQ3IvWVh5VVpxeUt1RVZJTkVFaXVDNUtBQmtBajlJCnpPTWJiU1RtZWxTOEF4RzdvenB6ajBZTEhOMEtSUk9KV3lIQ3k3WklrRUdkclRPMjF3M0c4Qi9od3FqanV6Vi8KTzhZNnVRUVJXSmRsb2JSRHFoUTVIUFlaUElIRGJZLzhCMXVwcm9RcU1Xc0NYYjN5V21uZy9mSzJWRUU4RXRXbQpLMW5xNlJMbkhOU0JzRmpQdEk1ZmxZN0cwTFdxQ1MxTWRVUEtoZm9xUkJRcU04VDhpTFRURTIweHZkRXY5MEJ3CnpNTGNtckJheFJOSVViVzZNZTJEbDZ2dnJ4WE1CbjR0R21zYzVBemE3Zmk0RmF4UC9wRkV4RW1xZ01kVjVNb2wKRHRiaE9CazRSK1VQTTc5Z3MxZ2Q1NHFpcUpGZHdJemp6MW1qbU1rUkYvSU5BbXlxS1FLNHI2WGJnMUFpVUh5QgpudmYzOWdOQVY5d21VSnlMTkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","url":"https://localhost:8443/mutate-pods"},"name":"aks-webhook-admission-controller.azmk8s.io","rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}]}]}
  creationTimestamp: "2021-03-10T06:00:16Z"
  labels:
    admissions.enforcer/disabled: "true"
  managedFields:
  - apiVersion: admissionregistration.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:admissions.enforcer/disabled: {}
      f:webhooks:
        .: {}
        k:{"name":"aks-webhook-admission-controller.azmk8s.io"}:
          .: {}
          f:admissionReviewVersions: {}
          f:clientConfig:
            .: {}
            f:caBundle: {}
            f:url: {}
          f:failurePolicy: {}
          f:matchPolicy: {}
          f:name: {}
          f:namespaceSelector: {}
          f:objectSelector: {}
          f:reinvocationPolicy: {}
          f:rules: {}
          f:sideEffects: {}
          f:timeoutSeconds: {}
    manager: kubectl_v1.18.8
    operation: Update
    time: "2021-03-10T06:00:16Z"
  name: aks-webhook-admission-controller
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2VENDQXRHZ0F3SUJBZ0lSQUxRNGdtZEIxMFZXTXdaZVIxU3c5UW93RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdJQmNOTWpFd016RXdNRFUwTlRReldoZ1BNakExTVRBek1UQXdOVFUxTkROYQpNQTB4Q3pBSkJnTlZCQU1UQW1OaE1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBCjBvVWthNnV3cGFERHBNMXIwcitKaEFWcG1JUzFpb3RlZHlMbGlsdDBJOVZBUGtCWFA3TVZUR0tkby8xdzdtS3kKdm9kU0JZNHRidzZ6SVhqd3N5TzhSZzYrYjFkTTVBL2kxbDVmbzRmbmtuOURFM0toSzRZTnAzZlhRVVMvbzJFSAozNFFHMyt5dmtwWThkVFhvRTdkM05EM3N3RTVYRHJqVlpyVmx2YXgwUzlxd1dqM2owQXRYV3FlQ0QxYWEyQndYCmMvcjNuVis4OFNlaTFjcDVTR1ljWEROYlRTQU1HQm9SdVM4a0dRYi9za3N0ZkxsSHlzVVM3ZmJaL2pKMEJlUDIKcWErd2l3OWpPOG9RMWVmLzRoTjJLeVduclNjY2hCeHdMNzdDMGlsUTlzWEozUW9PNFhRa0MwUGpNMnlkN2NFWApHZXhHV0NLMzAvay8rVWVwSU11N25BSExwVHlBUGd0dDdOVW1wN045bStsSWNyV0s3Q0MwREhmWlEycHhuV1FtCnhsaDVheVd4b3pSa2o2RC9wTHRIWDRqZDNrbmkxckJnSEZabzRFdHZ1MmNPU2YrT0txSGZ6dXBXbXZuM21FL0kKcU14d0tDaGhYZFV1WlBuRXhTNGpYWk1kZHdXTlZhNVRKdSthbkxwMVcrOForbGwwRHVneUhiSVRweDFCeXdoRwp5SkwwSEJPYWpuQTQ4ekFLSE52RDBVMUo4YTR1M09xa1BIRnhxR1QxY3c4dXVKWVZET1BFNWE4ZEpGcncwV0FSCmNoQjV1QlArb0N1UEI4M3JITCtrb1FKRlBnc3JwRlhBN3NEZUhid0Vrb2FZOC9pcW5BVkVyOGxnbllKVDJNTjMKd0VsUjVLNkl3a0VCM29hOGUyL2tnQUpDOU5yUUNCQU45SkY5bEMrZ2FIc0NBd0VBQWFOQ01FQXdEZ1lEVlIwUApBUUgvQkFRREFnS2tNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGQXFKNjloV2I5TG9sbUhFCjFndHczMjRpd3l5Zk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQVVIeGFQenlQYk5PSkRxZTdJM2xhUmtGcGUKcW9hYjFnK2FiVW1Ua0JiOW0rQmxlT1hNNUczd1haZXhicFlDaEozM1NKdWVPRTU4NFIxa1lncjQzVEVLTGttQgo1VHJRYklGcS9TT1Rha0RLbmhmRXFCRHBYZTQxeE5MTzM3S1Jnd2ZDZ0VBUU9Zbm85Szh5REdsMk9yY092SkViClFmakNsR2phMGt0NnBFanYzdmlKSnR2S05LL0VESFhOYXRsZ2k5U2daUnM4NkkxOW1mcmI0ZVBpWldKU3ZyVGcKdFk5eFdJNTNhYmxEUXczRndvNmZPdjBvWDN3UHhZdkp3OGFjSEM0WW1vWXcvQWtpUUxRV0NUV1ZQRG1OZGVrbwo2WlVjK2RVeG9oNmhOZVg3V1creXNxc1cwK1gwMjBiemVIQ3IvWVh5VVpxeUt1RVZJTkVFaXVDNUtBQmtBajlJCnpPTWJiU1RtZWxTOEF4RzdvenB6ajBZTEhOMEtSUk9KV3lIQ3k3WklrRUdkclRPMjF3M0c4Qi9od3FqanV6Vi8KTzhZNnVRUVJXSmRsb2JSRHFoUTVIUFlaUElIRGJZLzhCMXVwcm9RcU1Xc0NYYjN5V21uZy9mSzJWRUU4RXRXbQpLMW5xNlJMbkhOU0JzRmpQdEk1ZmxZN0cwTFdxQ1MxTWRVUEtoZm9xUkJRcU04VDhpTFRURTIweHZkRXY5MEJ3CnpNTGNtckJheFJOSVViVzZNZTJEbDZ2dnJ4WE1CbjR0R21zYzVBemE3Zmk0RmF4UC9wRkV4RW1xZ01kVjVNb2wKRHRiaE9CazRSK1VQTTc5Z3MxZ2Q1NHFpcUpGZHdJemp6MW1qbU1rUkYvSU5BbXlxS1FLNHI2WGJnMUFpVUh5QgpudmYzOWdOQVY5d21VSnlMTkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    url: https://localhost:8443/mutate-pods
  failurePolicy: Ignore
  matchPolicy: Exact
  name: aks-webhook-admission-controller.azmk8s.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
