apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2021-03-10T06:59:02Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:phase: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-10T06:59:02Z"
  name: ingress-basic
spec:
  finalizers:
  - kubernetes
