apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/azure-disk
    volumehelper.VolumeDynamicallyCreatedByKey: azure-disk-dynamic-provisioner
  creationTimestamp: "2021-03-11T07:18:10Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: eastasia
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:pv.kubernetes.io/bound-by-controller: {}
          f:pv.kubernetes.io/provisioned-by: {}
          f:volumehelper.VolumeDynamicallyCreatedByKey: {}
        f:labels:
          .: {}
          f:failure-domain.beta.kubernetes.io/region: {}
      f:spec:
        f:accessModes: {}
        f:azureDisk:
          .: {}
          f:cachingMode: {}
          f:diskName: {}
          f:diskURI: {}
          f:fsType: {}
          f:kind: {}
          f:readOnly: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:claimRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
          f:resourceVersion: {}
          f:uid: {}
        f:nodeAffinity:
          .: {}
          f:required:
            .: {}
            f:nodeSelectorTerms: {}
        f:persistentVolumeReclaimPolicy: {}
        f:storageClassName: {}
        f:volumeMode: {}
      f:status:
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-11T07:18:10Z"
  name: pvc-ba876d4b-bac5-4f15-b853-a1c8b0199b7c
spec:
  accessModes:
  - ReadWriteOnce
  azureDisk:
    cachingMode: ReadOnly
    diskName: kubernetes-dynamic-pvc-ba876d4b-bac5-4f15-b853-a1c8b0199b7c
    diskURI: /subscriptions/442f0218-2057-41f9-8c35-1dfcbc4691c0/resourceGroups/mc_ohnewakscluster-rg_ohnewakscluster_eastasia/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-ba876d4b-bac5-4f15-b853-a1c8b0199b7c
    fsType: ""
    kind: Managed
    readOnly: false
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: kube-backups-katafygio
    namespace: default
    resourceVersion: "222636"
    uid: ba876d4b-bac5-4f15-b853-a1c8b0199b7c
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - eastasia
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  volumeMode: Filesystem
